server:
  port: 8080  # 애플리케이션 실행 포트

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/udigo  # MySQL 데이터베이스 URL (본인 DB명으로 변경)
    username: udigo  # MySQL 사용자명
    password: udigo  # MySQL 비밀번호 (설정한 값으로 변경)
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 설정

  jpa:
    hibernate:
      ddl-auto: update  # (create, update, validate, none 중 선택)
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리 예쁘게 출력
    show-sql: true  # 실행되는 SQL을 콘솔에 출력

  thymeleaf:
    cache: false  # Thymeleaf 캐시 비활성화 (HTML 변경 사항 즉시 반영)
